name: mdi
description: Material Design Icons for Flutter from the materialdesignicons.com community.
version: 6.0.0
homepage: https://github.com/vyperium/mdi-dart

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: Material Design Icons
      fonts:
        - asset: fonts/materialdesignicons-webfont.ttf
